### ISSUE TITLE
Produce single chunk file.

### ISSUE THREAD

**Issue by tft-kyrre** [TromsFylkestrafikk/ragnarok-fara#7]
Chunks consisting of multiple files should be compressed and stored in a single archive file. See [ragnarok#60](https://github.com/TromsFylkestrafikk/ragnarok/issues/60).

**Comment by tfk-kaare** [comment]
tromsfylkestrafikk/ragnarok#60 is committed. The only source not yet completely updated with this refreshed API is sink-consat, which still has to be fetched from its issue brach `7-one-file`.

**Comment by tft-kyrre** [comment]
@tft-kaare  Ragnarok-sink main branch is not updated with the latest changes.

**Comment by tfk-kaare** [comment]
fixed. tromsfylke + github + ssh = unstable
